[project]
name = "data-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clickhouse-driver>=0.2.10",
    "dotenv>=0.9.9",
    "websockets>=15.0.1",
]
